#!/usr/bin/env python3
"""
tezOS bitmap font rasterizer.

Converts a TTF into a fixed-size 8-bit alpha-coverage glyph bitmap table,
emitted as a C header. Alpha-coverage (not 1bpp) so draw_text can blend
against any foreground color from the palette at draw time, rather than
baking in one fixed color per font asset.

Usage: python3 rasterize_font.py <ttf_path> <pixel_size> <c_identifier> <out_header>
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FIRST_CHAR = 32   # space
LAST_CHAR = 126   # ~

def rasterize(ttf_path, px_size, ident, out_path, json_out_path=None):
    font = ImageFont.truetype(ttf_path, px_size)

    glyphs = []
    max_h = 0
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        ch = chr(code)
        # Generous canvas, we'll crop to actual ink bbox after.
        canvas = Image.new("L", (px_size * 2 + 8, px_size * 2 + 8), 0)
        draw = ImageDraw.Draw(canvas)
        draw.text((4, 4), ch, font=font, fill=255)
        bbox = canvas.getbbox()
        if bbox is None:
            # blank glyph (space) — zero-size bitmap, advance still recorded
            advance = draw.textlength(ch, font=font)
            glyphs.append({
                "code": code, "w": 0, "h": 0, "xoff": 0, "yoff": 0,
                "advance": round(advance), "pixels": []
            })
            continue
        left, top, right, bottom = bbox
        w = right - left
        h = bottom - top
        cropped = canvas.crop((left, top, right, bottom))
        pixels = list(cropped.getdata())
        advance = draw.textlength(ch, font=font)
        max_h = max(max_h, h)
        glyphs.append({
            "code": code, "w": w, "h": h,
            "xoff": left - 4, "yoff": top - 4,
            "advance": round(advance), "pixels": pixels
        })

    total_bytes = sum(len(g["pixels"]) for g in glyphs)

    with open(out_path, "w") as f:
        f.write(f"/* Auto-generated by rasterize_font.py — do not hand-edit.\n")
        f.write(f"   Source: {ttf_path} at {px_size}px. tezOS default font asset. */\n")
        f.write(f"#pragma once\n#include <stdint.h>\n#include \"../tezos_gfx.h\"\n\n")

        # emit each glyph's bitmap as its own array (skip empties)
        for g in glyphs:
            if g["w"] == 0:
                continue
            arr_name = f"{ident}_bmp_{g['code']}"
            vals = ",".join(str(p) for p in g["pixels"])
            f.write(f"static const uint8_t {arr_name}[] = {{{vals}}};\n")

        f.write(f"\nstatic const struct tezos_glyph_generic {ident}_glyphs[{LAST_CHAR - FIRST_CHAR + 1}] = {{\n")
        for g in glyphs:
            bmp_ref = f"{ident}_bmp_{g['code']}" if g["w"] > 0 else "0"
            f.write(f"    {{ {g['w']}, {g['h']}, {g['xoff']}, {g['yoff']}, {g['advance']}, {bmp_ref} }}, "
                    f"/* '{chr(g['code']) if g['code'] not in (34,92) else '?'}' ({g['code']}) */\n")
        f.write("};\n\n")

        f.write(f"#define {ident.upper()}_FIRST_CHAR {FIRST_CHAR}\n")
        f.write(f"#define {ident.upper()}_LAST_CHAR {LAST_CHAR}\n")
        f.write(f"#define {ident.upper()}_PIXEL_SIZE {px_size}\n")
        f.write(f"#define {ident.upper()}_LINE_HEIGHT {int(px_size * 1.25)}\n")

    print(f"{ident}: {LAST_CHAR - FIRST_CHAR + 1} glyphs, {total_bytes} bytes of bitmap data -> {out_path}")

    if json_out_path:
        import json, base64
        json_glyphs = {}
        for g in glyphs:
            json_glyphs[g["code"]] = {
                "w": g["w"], "h": g["h"], "xoff": g["xoff"], "yoff": g["yoff"],
                "advance": g["advance"],
                # base64-pack the raw alpha bytes — same data as the C array,
                # just compact enough to inline in a browser-side JS file
                # instead of a JSON number array (which bloats ~3-4x larger).
                "px": base64.b64encode(bytes(g["pixels"])).decode("ascii") if g["pixels"] else ""
            }
        out_json = {
            "name": ident, "pixelSize": px_size, "lineHeight": int(px_size * 1.25),
            "firstChar": FIRST_CHAR, "lastChar": LAST_CHAR, "glyphs": json_glyphs
        }
        with open(json_out_path, "w") as jf:
            json.dump(out_json, jf)
        print(f"  also wrote JS-consumable JSON -> {json_out_path}")

if __name__ == "__main__":
    ttf, px, ident, out = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4]
    json_out = sys.argv[5] if len(sys.argv) > 5 else None
    rasterize(ttf, px, ident, out, json_out)
